name: Continuous Integration

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP 8.2 with Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: dist-${{ runner.os }}-php-${{ hashFiles('composer.lock') }}
          restore-keys: |
            dist-${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction
       
      - name: Run Linter (PHP CS Fixer)
        run: composer lint

      - name: Run Static Analysis (PHPStan)
        run: composer analyse
